server:
  port: 8099

spring:
  application:
    name: parking-project

  banner:
    location: banner/banner-${spring.profiles}.txt

  profiles:
    active: dev
    include:
      - datasource



logging:
  level:
    org.hibernate.SQL: DEBUG
    com.kr.parking_project: DEBUG
    org.springframework.secruity: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


token:
  expiration_time: 86400000
  secret: user_token