spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 20
        max-page-size: 500

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #        show_sql: true
#    datasource:
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://211.206.132.104:3306/msa
#      username: root
#      password: 123
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
##        show_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

---
spring:
  profiles: test

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://nearpp.net:13306/next_project_manager
    username: project_manager
    password: project-manager!@34

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100

decorator:
  datasource:
    p6spy:
      enable-logging: true

---
spring:
  profiles: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://next-energy-korea-database.cjlqdu3g7mlh.ap-northeast-2.rds.amazonaws.com:3306/next_project_manager
    username: project_manager
    password: project-manager!@34

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100

decorator:
  datasource:
    p6spy:
      enable-logging: false