server:
  port: 8099

spring:
  application:
    name: parking-project

  banner:
    location: banner/banner-${spring.profiles}.txt

  profiles:
    active: dev
    include:
      - datasource



logging:
  level:
    org.hibernate.SQL: DEBUG
    com.kr.parking_project: DEBUG
    org.springframework.secruity: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400